### ISSUE TITLE
Hamagen showed an Erroneous Exposure event, what could be the reason?

### ISSUE THREAD

**Issue by denisvitchevsky** [MohGovIL/hamagen-react-native#113]
Got an erroneous detection for a date that's prior to the install date, in a city that I didn't visit that day. 

![photo_2020-03-27_19-30-11](https://user-images.githubusercontent.com/18900708/77778012-682ade80-7061-11ea-98b9-48079c5c55f2.jpg)

**Comment by AlmaMOH** [comment]
Hey @denisvitchevsky ,

We apologize for this.

From what we can tell, there was an error in the database of the validated COVID-19 patients.

This was probably caused because an errorneus duration of time at a particular place was added (i.e. `startTime` was set to `13.03.20`, but the `endtime` is now.

Please note that the process of adding the time duration and the coordinates of a particular place  is currently a **manual** one (and is done by volunteers that "geocode" raw data of epidemiological investigations).
