### ISSUE TITLE
App data is updated only after clearing storage & cache

### ISSUE THREAD

**Issue by arielgee** [MohGovIL/hamagen-react-native#120]
The app displayed data from 23.03 (the day I installed it) for 5 days. The results were updated to 28.03 only after I cleared storage & cache.

**Comment by AlmaMOH** [comment]
Hey @arielgee ,

Apologies for the late reply (on #78).

The app fetches the database of locations and times of the validated COVID-19 patients every X minutes. 

Since we haven't integrated #124 yet, we always state on the home screen of Hamagen the initial date that the app began recording coordinates and time (**locally**).
