### ISSUE TITLE
Repeating notifications for the same event

### ISSUE THREAD

**Issue by sergeykad** [MohGovIL/hamagen-react-native#167]
Every few hours I am getting a notification about the same potential exposure. Should not it notify only once about each event? I press the button that I was not at the location each time, but still getting the same notification over and over.

**Comment by amosshahor** [comment]
It also happens to me. 
It's annoying, but the worst thing is that like any alarm system, false alarms can kill its effectivity because it makes people turn it off or start ignoring its notifications.

![image](https://user-images.githubusercontent.com/13424869/78232497-03e2a180-74dd-11ea-943a-5c332225697d.png)

**Comment by emanuelb** [comment]
did you use the last version? this issue should be fixed, see https://github.com/MohGovIL/hamagen-react-native/issues/144#issuecomment-607509232 and #145

**Comment by amosshahor** [comment]
Apparently I wasn't.
Is there a reason the app doesn't automatically update? 
I'm pretty sure the rest of my apps do (not 100%, relatively new phone).

**Comment by kaplanlior** [comment]
Hi @sergeykad, @amosshahor - thanks for reporting. The issue has been fixed in previous versions.
