### ISSUE TITLE
Exposure radius and time - too strict?

### ISSUE THREAD

**Issue by aviezerl** [MohGovIL/hamagen-react-native#32]
Isn't 500 meters for 1 millisecond a bit strict? 

```js
    meterRadius: 500,
    intersectMilliseconds: 1, // 1 milli
```
The official guidelines are 2 meters for 15 minutes.

**Comment by olegsu** [comment]
Nice catch! 
Also, what are the battery implications on this config? just wondering

**Comment by sergeykad** [comment]
> Isn't 500 meters for 1 millisecond a bit strict?
> 
> ```js
>     meterRadius: 500,
>     intersectMilliseconds: 1, // 1 milli
> ```
> 
> The official guidelines are 2 meters for 15 minutes.

Geolocation data is usually not precise and easily can be off by a kilometer. Keeping that in mind the used numbers are OK.

**Comment by MiriShalev** [comment]
Thanks @aviezerl and @olegsu !

Since both the location data of validated COVID-19 patients and the device's geolocation are not accurate (at least not to the degree we wished for), the app detects intersections with a large radius (for now). 

That being said, please note that the app never explicitly says that you've been near a validated COVID-19 case. The app **always** asks:

![App asks if you were near a validated case](https://lh3.googleusercontent.com/D0vk7O06JnDo9VTHk7b2_cUF45AG7lVTJ6zAKzkaKqJBZzbtf5bYsk4fK23MiRJUBQ=w2556-h1325-rw)


The reason for this is that inside the sick people's JSON there's a comment section which is usually way more descriptive than coordinates.

**Comment by neryos** [comment]
I suggest you document the reasoning behind this design decision in the code :)
