### ISSUE TITLE
Hard Coded Key in android/app/src/debug/res/values/

### ISSUE THREAD

**Issue by AR533** [MohGovIL/hamagen-react-native#54]
https://github.com/MohGovIL/hamagen-react-native/blob/160eb95869de64cc4e3d0dc476bab325c8a000f7/android/app/src/debug/res/values/strings.xml#L4

As a security person, I would want to avoid from hard coded keys.
If I got it right, the debug mode will allow an attacker to use this to impersonate the application as legitimate request and contaminate the db.

Let me know what you think and if this could be change, thanks.

**Comment by dotansimha** [comment]
I think there is no way to avoid it? I mean, it can be removed from the source code, but it will be there anyway after compiling it and could be accessed anyway. 

TBH, I'm more concerned about this commit (because it was not squashed and because it too easy to guess if it's the real one...): https://github.com/MohGovIL/hamagen-react-native/commit/f57cf6f6ae76f18649be67f88e5692c2e2091286 @MiriShalev ? ...

**Comment by MiriShalev** [comment]
@AR533 Thanks!

We agree with @dotansimha on this- any simple reversing of the app would expose the key. We hope that when we'll have a CI in place we can avoid it.

@dotansimha the **release keystore** was never included in the code base. We agree that storing plaintext passwords in code is a terrible anti pattern.

**FYI, we generated new passwords for the release keystore.**

We'll see what we can do about squashing / removing it from the history. Thank you!
