### ISSUE TITLE
Make locations comparison more efficient

### ISSUE THREAD

**Issue by oleiba** [MohGovIL/hamagen-react-native#58]
Currently, `checkSickPeople` is doing a fetch to the base URL (locations DB) and gets it in its entirety.
Second, it iterates over the sick people locations DB, end for each document it iterates over the local DB which is O(m*n) (where m and n are the remote and local DB sizes).
As infections will become large (hopefully it wouldn't) this may be a bottleneck for the application, causing memory and performance issues.
While it is mostly a server-side work for enabling a more flexible API, I can try to make some suggestions.

1. Get only the locations that haven't been inspected yet. No need to fetch and check locations that were already checked against the local DB since no new intersections can be found there.
This can be implemented by utilizing a cursor, depending on the backend DB.
2. Get only locations that occurred only after the application's first tracking. It is probably information the server can have on the user anyway (it can easily log its first API call), so it doesn't leak any additional information.
3. Other optimizations depend on the amount of data we are willing to expose.
If we're willing to give some rough boundaries for a user's locations, that can cut the amount of data significantly in the vast majority of cases.
4. For making the iteration more efficient we can consider sorting the two lists (e.g. by time) and then working with 2 pointers for comparison and advancing.

**Comment by akruman** [comment]
split the json db into several files, each spanning a another day.

**Comment by AlmaMOH** [comment]
Thanks @oleiba and @akruman .

Apologies for the late response.

We're well aware of the O(m*n) time complexity in local location comparison. Honestly, we did try to implement an O(m) solution  (m - number of sick people coordinates) but due to the lack of time we didn't. 

We thought about an efficient prefix search using several [Geohashes](https://en.wikipedia.org/wiki/Geohash) and even use quantizations methods such as [SpaceTime Hash](https://github.com/yjlou/2019-nCov/blob/master/lib_sthash.js).

We already began working on incremental updates. I think a saving a local cursor and queryinbg with it makes a lot of sense.

Thanks again for all your good points!
