### ISSUE TITLE
Fine granular Intersection calculation required

### ISSUE THREAD

**Issue by ariellev** [MohGovIL/hamagen-react-native#59]
At the current release, the criterion for finding an intersection between a corona carrier to a given user on the production environment is "500 meter for 1 millisecond", which obviously does not make any sense.  

./config/config.ts

Is: 

```javascript   
{
..
   meterRadius: 500,
    intersectMilliseconds: 1, // 1 milli
}
```

Should:

```javascript   
{
..
   meterRadius: 10,
    intersectMilliseconds: 1000 * 60 * 15, // e.g. 15 minutes 
}
```

**Comment by ItayElgazar** [comment]
why 10? meterRadius should be 2

**Comment by ariellev** [comment]
Of course GPS signals tend to hope, so we need to account for that

**Comment by ItayElgazar** [comment]
Still don't get why 10 :) from where did you get this number?

**Comment by ariellev** [comment]
intuition, like 2 meters would be the ideal case, I agree, but I am not sure it's realistic taking into account GPS hoping. So I would recommend to drop the radius to the 10-20 meters area, and keep on optimizing from there.

**Comment by henry-hz** [comment]
ops, just sent a PR for 200m, because we walk 100m in 1 min, and it's feasible to think that people leave the celular in the car, or near him. 10m doesn't cover the GPS lack of accuracy... see [here](https://www.gps.gov/systems/gps/performance/accuracy/#problems) and [here](https://www.researchgate.net/publication/306052159_Horizontal_accuracy_and_applicability_of_smartphone_GNSS_positioning_in_forests)

**Comment by yehudit-vizel-Moh** [comment]
Thanks @ariellev, @ItayElgazar and @henry-hz !

See more details here:
https://github.com/MohGovIL/hamagen-react-native/issues/32
