### ISSUE TITLE
Begin CI Efforts (Travis/CircleCI/Github Actions)

### ISSUE THREAD

**Issue by MiriShalev** [MohGovIL/hamagen-react-native#96]
#94  and #95  are blockers for this.

**Comment by danielvrog** [comment]
I started with some basic flow:
https://github.com/danielvrog/hamagen-react-native/tree/festure/add-basic-public-CI-with-GitHub-Actions

If you are interested in getting Sonar scan - please add relevant secrets and I will parametrize the job.

IMHO the basic CI need to run in order to allow contribution while publishing apps may run with internal MOH CI.
